# Generated by Django 4.2 on 2023-04-11 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_newsarticle_author_newsarticle_image1'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewsArticle',
            new_name='latest',
        ),
    ]
