# Generated by Django 4.2 on 2023-04-16 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_category_cat_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
