# Generated by Django 4.2 on 2023-04-17 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_category_name_alter_category_slug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='news',
        ),
    ]
