# Generated by Django 4.2 on 2023-04-17 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_news'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='status',
        ),
        migrations.RemoveField(
            model_name='category',
            name='trending',
        ),
    ]
